### ISSUE TITLE
plain (equivalent to unsafe but with xss protection)

### ISSUE THREAD

**Issue by mren** [snd/kup#2]
hey snd,

sometimes i want to add plain text without a span, but want to have the code xss safe.

how about adding a new method `builder.plain`  which does xss and does not add an element

if i use `unsafe` for this a newline is prepended to each string.

i want to do the following

```coffeescript

builder.p ->
  builder.plain 'Hello '
  builder.strong 'name'
  builder.plain ', how are you?'
```

which should result in

```
<p>Hello name, how are you</p>
```

but with unsafe i receive

```
<p>
hello
<strong>name</strong>
, how are you
```

which will result in

hello **name** , how are you

notice the space between the strong element and the semicolon
cheers mark

**Comment by snd** [comment]
the cause of the problem wasn't that a newline was added before each unsafe string
but that a newline was added after each tag (the strong tag in this case).

as of version `1.4.0` newlines are no longer added automatically which removes the problem.
the now recommended way to get pretty printing that is described in the readme doesn't reintroduce it.

escaped (xss safe) plaintext can be added with `builder.safe(string)`
